services:
  code-analysis:
    build: .
    volumes:
      - ./output:/output
    environment:
      - GIT_REPO=${GIT_REPO:-https://github.com/chrissssss/tokei-container}
    command: ["sh", "-c", "./analyze.sh"]
